language: cpp

os:
  - osx

sudo: required

#env: GCC_VERSION=5 CPP=11 COMPILER=g++-5 CXX=g++-5 CC=gcc-5

install:
  - brew update
  - brew install python3
  - sudo mkdir /opt/qt
  - rm -r '/usr/local/lib/python2.7/site-packages/numpy'
  - rm '/usr/local/bin/f2py'
  - brew install numpy
  - brew info opencv3
  - brew install opencv3
  - ls /usr/local/Cellar/opencv
  - OPENCV_VERSION="$(ls -1 /usr/local/Cellar/opencv)"
  - echo $OPENCV_VERSION
  - export OPENCV_DIR=/usr/local/Cellar/opencv/$OPENCV_VERSION
  - echo $OPENCV_DIR
  - echo $PWD
  - cd build
  - wget https://github.com/livecv/livecv-deploy-kit/archive/master.zip
  - unzip master.zip
  - mv livecv-deploy-kit-master/* .
  - wget http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-mac-x64-clang-5.7.0.dmg
  - ls
  - hdiutil attach -mountpoint installqt qt-opensource-mac-x64-clang-5.7.0.dmg
  - ls installqt
  - ./installqt/qt-opensource-mac-x64-clang-5.7.0.app/Contents/MacOS/qt-opensource-mac-x64-clang-5.7.0 --script resources/install-qt-macos.qs --verbose --silent -platform minimal
  - ls /opt/qt/5.7/clang_64
  - export QTDIR=/opt/qt/5.7/clang_64

script:
  - ls
  - python3 livepm/main.py build .. macos_clang_64
  - ls
  - find .
  - python3 livepm/main.py deploy .. macos_clang_64
  - python3 livepm/main.py makedoc ..
  - ls

before_deploy:
  - ls *.tar.gz
  - export LIVECV=$(ls live*.tar.gz | tail -n +1 | head -1)
  - export LIVECV_DOC=$(ls doc*.tar.gz | tail -n +1 | head -1)
  - echo ${LIVECV}
  - echo ${LIVECV_DOC}

deploy:
  provider: releases
  api_key:
    - secure: "uoyLbdtkGr8IDnyECv747iVkAsxMdqQR1v9wfwbEj4lsSHZ2E+Y3ShZMmV2AZUK86ajksBOvfMUYVo8P2JTQUsQtduu9SAIFF2MxxIVQbwmdF27cvnSUDFQjkU6h2UDNbgdi2I6rtH2g1Adhx/C45my0NQdvbhB9fEV3H+Z8g0YmoBDu3MZFGZknpf/PpNzaoGtHATo+0VooqCrAZhR9M1igGQF2ibU8z8E9xm04ehSjlMoXWv15GWmwOmkjQSe/mkeOUJ9Bl2LuIk3PcIv7uJNle5GgteQM+++iru59kZSXTLqih2peZVT7BLQ3c4gUZCtLASFPXwoQH2n4VMz4OeGv4b9LMw9bvwQ+eM8//enDDyIy2fP6KQu2BdLIScNX6B4eitxVMEcOXRHOc4xmlXqNloCOtGONaZ7w3OnwPj/O38ThM8c4riq1sh1TFBabRge8VGkBiKU3cDYPdGM2uMxST0swcrgBqu0UZ45xCftbF1tqJjs6K6ZS1v298KVlHcxyfdSJTDKCEOyTJXH6at2yYhQZ9RKrimZE5aiK0h3dsflKrmMXKDWWmQmAB7WxRQhNjEDuULvhq0f5z+oLDbL1hGSYM09196fyUDLeRY7wdYoIVaH3ebk5j6b+ar9RaQ16MoERBxR1ULUcs5gJHxCWPwyb4jRZBeMJJwzNF3Q="
  file_glob: true
  file:
    - "${LIVECV}"
    - "${LIVECV_DOC}"
  skip_cleanup: true
  on:
    tags: true
